apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: stage-grpc-backendconfig
spec:
  # This overrides the loadbalancer health check for grpc and api ports.
  # The api port returns an error message which would otherwise fail health.
  # The grpc port doesn't expect HTTP health checks.
  healthCheck:
    port: 26657
    requestPath: /
    type: HTTP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/app-protocols: '{"grpc":"HTTP2"}'
    cloud.google.com/backend-config: '{"default": "stage-grpc-backendconfig"}'
  name: rpcnodes
spec:
  type: ClusterIP
  selector:
    grouplb: validator
  ports:
  - protocol: TCP
    targetPort: 26656
    port: 26656
    name: p2p
  - protocol: TCP
    targetPort: 26657
    port: 26657
    name: rpc
  - protocol: TCP
    targetPort: 1317
    port: 1317
    name: api
  - protocol: TCP
    targetPort: 9090
    port: 9090
    name: grpc

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/app-protocols: '{"grpc":"HTTP2"}'
    cloud.google.com/backend-config: '{"default": "stage-grpc-backendconfig"}'
  name: rpcnodes-ext
spec:
  type: LoadBalancer
  selector:
    grouplb: validator
  sessionAffinity: "ClientIP"
  ports:
  - protocol: TCP
    targetPort: 26657
    port: 26657
    name: rpc
  - protocol: TCP
    targetPort: 1317
    port: 1317
    name: api
  - protocol: TCP
    targetPort: 9090
    port: 9090
    name: grpc
    
