---
apiVersion: v1
kind: Service
metadata:
  name: rpcnodes
spec:
  type: ClusterIP
  selector:
    grouplb: validator
  ports:
  - protocol: TCP
    targetPort: 26656
    port: 26656
    name: rpc
  - protocol: TCP
    targetPort: 26657
    port: 26657
    name: rpcw
  - protocol: TCP
    targetPort: 1317
    port: 1317
    name: api
  - protocol: TCP
    targetPort: 9090
    port: 9090
    name: grpc

---
apiVersion: v1
kind: Service
metadata:
  name: rpcnodes-ext
spec:
  type: LoadBalancer
  selector:
    grouplb: validator
  sessionAffinity: "ClientIP"
  ports:
  - protocol: TCP
    targetPort: 26657
    port: 26657
    name: rpcw
  - protocol: TCP
    targetPort: 1317
    port: 1317
    name: api
  - protocol: TCP
    targetPort: 9090
    port: 9090
    name: grpc
    
