apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: instagoric

resources:
  - ../local

configMapGenerator:
  - name: instagoric-release
    literals:
    - CHAIN_ID=agoriclocal-1
    - BOOTSTRAP_CONFIG=@agoric/vats/decentral-core-config.json
    - HONEYCOMB_DATASET=agoriclocal
