apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorer
spec:
  selector:
    matchLabels:
      app: explorer
  replicas: 1
  template:
    metadata:
      labels:
        app: explorer
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: explorer
          image: "agoric/pingpub:20220511"
          command: ["/bin/sh"]
          args: ["-x", "/entrypoint/entrypoint.sh"]
          env:
            - name: NETNAME
              valueFrom:
                configMapKeyRef:
                  name: instagoric-release
                  key: NETNAME
            - name: NETDOMAIN
              valueFrom:
                configMapKeyRef:
                  name: instagoric-release
                  key: NETDOMAIN
                  optional: true
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          ports:
            - containerPort: 8080
              name: web
          volumeMounts:
            - name: entrypoint
              mountPath: /entrypoint
          resources:
            limits:
              cpu: 1000m
              ephemeral-storage: 5Gi
              memory: 2Gi
            requests:
              cpu: 1000m
              ephemeral-storage: 5Gi
              memory: 2Gi
      volumes:
        - name: entrypoint
          configMap:
            name: explorerentrypoint
