apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: instagoric

resources:
  - ../../bases/shared
  - ../../bases/primaryvalidator
#  - ../../bases/validators
#  - ../../bases/seed
#  - ../../bases/ag-solo-manual
#  - ../../bases/ag-solo-tasks

configMapGenerator:
  - name: instagoric-release
    literals:
    - CHAIN_ID=agoriclocal-1
    - BOOTSTRAP_CONFIG=@agoric/vats/decentral-core-config.json
    - HONEYCOMB_DATASET=instagoric-local
    - VOTING_PERIOD=2m

patches:
  - target:
      kind: Service
      name: validator-primary
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30657
  - target:
      kind: StatefulSet
      name: validator-primary
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 2000m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 2000m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 4Gi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 2Gi
