apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: instagoric

resources:
  - ../../bases/shared
  - ../../bases/primaryvalidator
#  - ../../bases/validators
#  - ../../bases/seed
#  - ../../bases/ag-solo-manual
#  - ../../bases/ag-solo-tasks

patches:
  - target:
      kind: Service
      name: validator-primary
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30657
  - target:
      kind: StatefulSet
      name: node
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: 
          name: CHAIN_ID
          valueFrom:
            configMapKeyRef:
              name: instagoric-release
              key: CHAIN_ID
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: BOOTSTRAP_CONFIG
          valueFrom:
            configMapKeyRef:
              name: instagoric-release
              key: BOOTSTRAP_CONFIG
  - target:
      kind: StatefulSet
      name: validator-primary
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 2000m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 2000m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 4Gi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 2Gi
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: HONEYCOMB_API_KEY
          valueFrom:
            secretKeyRef:
              name: telemetry-secrets
              key: HONEYCOMB_API_KEY
              optional: true
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: HONEYCOMB_DATASET
          valueFrom:
            configMapKeyRef:
              name: instagoric-release
              key: HONEYCOMB_DATASET
              optional: true
