receivers:
  otlp:
    protocols:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otelcol'
          scrape_interval: 5s
          static_configs:
            - targets: ['localhost:26660', 'localhost:26661']
  hostmetrics:
    collection_interval: 10s
    scrapers:
      paging:
      network:
      process:
        include: 
          names:
            - ".*node.*"
            - ".*xsnap-worker.*"
          match_type: regexp

  hostmetrics/disk:
    collection_interval: 10s
    scrapers:
      disk:
      filesystem:

exporters:
  stdout:

processors:
  memory_limiter:
      check_interval: 1s
      limit_mib: 4000
      spike_limit_mib: 800
  batch:
    send_batch_max_size: 200
    send_batch_size: 200

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [ memory_limiter, batch]
      exporters: []
    metrics:
      receivers: [prometheus, hostmetrics, hostmetrics/disk]
      processors: [ memory_limiter, batch]
      exporters: []
