---
apiVersion: v1
kind: Service
metadata:
  name: seed
spec:
  type: ClusterIP
  selector:
    app: seed
  ports:
  - protocol: TCP
    targetPort: 26656
    port: 26656
    name: rpc


---
apiVersion: v1
kind: Service
metadata:
  name: seed-ext
spec:
  type: LoadBalancer
  selector:
    app: seed
  sessionAffinity: "ClientIP"
  ports:
  - protocol: TCP
    targetPort: 26656
    port: 26656
    name: rpc
