name: Liquidation E2E tests

on:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label ||
    github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  run-e2e:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      docker_compose_command: |
        docker-compose -f test/e2e/docker-compose-liquidation.yml \
        --profile synpress up --build \
        --exit-code-from synpress
