name: Vaults E2E tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - edited
      - labeled
      - synchronize
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      network:
        description: 'Select the blockchain network for testing'
        required: false
        default: 'emerynet'
        type: choice
        options:
          - local
          - emerynet
          - devnet
          - ollinet
          - xnet
      phrase:
        description: 'The mnemonic phrase for the account to use in testing'
        required: false
        type: string
      a3p_image_tag:
        description: 'Docker image tag for the a3p chain to use in testing'
        required: false
        type: string

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  run-e2e:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      docker_compose_command: |
        docker compose -f test/e2e/docker-compose-vaults.yml \
        --profile $SYNPRESS_PROFILE up --build \
        --exit-code-from synpress
      AGORIC_NET: usman
      mnemonic_phrase: ${{ inputs.phrase }}
      a3p_image_tag: ${{ inputs.a3p_image_tag || 'latest' }}

    secrets: inherit
