name: Vaults E2E tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      network:
        description: 'Select the blockchain network for testing'
        required: false
        default: 'emerynet'
        type: choice
        options:
          - local
          - emerynet
      phrase:
        description: 'The mnemonic phrase for the account to use in testing'
        required: false
        type: string

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label ||
    github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  run-e2e:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      docker_compose_command: |
        docker-compose -f test/e2e/docker-compose-vaults.yml \
        --profile $SYNPRESS_PROFILE up --build \
        --exit-code-from synpress
      is_emerynet_test: ${{ github.event_name == 'schedule' || inputs.network == 'emerynet' }}
      mnemonic_phrase: ${{ inputs.phrase }}
