---
apiVersion: v1
kind: Service
metadata:
  name: validator-primary
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  selector:
    app: validator-primary
  ports:
  - protocol: TCP
    targetPort: 26657
    port: 26657
    name: rpc
  - protocol: TCP
    targetPort: 26656
    port: 26656
    name: p2p
  - protocol: TCP
    targetPort: 8002
    port: 8002
    name: sidekickprivate

---
apiVersion: v1
kind: Service
metadata:
  name: validator-primary-ext
spec:
  type: LoadBalancer
  selector:
    app: validator-primary
  sessionAffinity: "ClientIP"
  ports:
  - protocol: TCP
    targetPort: 26656
    port: 26656
    name: p2p
